from university_system.database_service.students import StudentsDatabase
from university_system.database_service.teachers import TeachersDatabase
from university_system.statistics.students import get_students_metrics
from university_system.statistics.teachers import get_teachers_metrics
